/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AccountRouteImport } from './routes/account';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AccountRoleRouteImport } from './routes/account/$role';
import { Route as AccountRoleUtilitiesRouteImport } from './routes/account/$role/utilities';
import { Route as AccountRoleTenantsRouteImport } from './routes/account/$role/tenants';
import { Route as AccountRoleRepairsRouteImport } from './routes/account/$role/repairs';
import { Route as AccountRolePropertiesRouteImport } from './routes/account/$role/properties';
import { Route as AccountRolePaymentsRouteImport } from './routes/account/$role/payments';
import { Route as AccountRoleLandlordsRouteImport } from './routes/account/$role/landlords';
import { Route as AccountRoleHomeRouteImport } from './routes/account/$role/home';
import { Route as AccountRoleAdd_propertyRouteImport } from './routes/account/$role/add_property';
import { Route as AccountRoleAddRepairsRouteImport } from './routes/account/$role/add-repairs';
import { Route as AccountRoleAddPaymentRouteImport } from './routes/account/$role/add-payment';
import { Route as AccountRolePropertyIdRouteImport } from './routes/account/$role/property/$id';
const RegisterRoute = RegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const AccountRoute = AccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const AccountRoleRoute = AccountRoleRouteImport.update({
    id: '/$role',
    path: '/$role',
    getParentRoute: () => AccountRoute,
});
const AccountRoleUtilitiesRoute = AccountRoleUtilitiesRouteImport.update({
    id: '/utilities',
    path: '/utilities',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRoleTenantsRoute = AccountRoleTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRoleRepairsRoute = AccountRoleRepairsRouteImport.update({
    id: '/repairs',
    path: '/repairs',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRolePropertiesRoute = AccountRolePropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRolePaymentsRoute = AccountRolePaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRoleLandlordsRoute = AccountRoleLandlordsRouteImport.update({
    id: '/landlords',
    path: '/landlords',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRoleHomeRoute = AccountRoleHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRoleAdd_propertyRoute = AccountRoleAdd_propertyRouteImport.update({
    id: '/add_property',
    path: '/add_property',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRoleAddRepairsRoute = AccountRoleAddRepairsRouteImport.update({
    id: '/add-repairs',
    path: '/add-repairs',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRoleAddPaymentRoute = AccountRoleAddPaymentRouteImport.update({
    id: '/add-payment',
    path: '/add-payment',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRolePropertyIdRoute = AccountRolePropertyIdRouteImport.update({
    id: '/property/$id',
    path: '/property/$id',
    getParentRoute: () => AccountRoleRoute,
});
const AccountRoleRouteChildren = {
    AccountRoleAddPaymentRoute: AccountRoleAddPaymentRoute,
    AccountRoleAddRepairsRoute: AccountRoleAddRepairsRoute,
    AccountRoleAdd_propertyRoute: AccountRoleAdd_propertyRoute,
    AccountRoleHomeRoute: AccountRoleHomeRoute,
    AccountRoleLandlordsRoute: AccountRoleLandlordsRoute,
    AccountRolePaymentsRoute: AccountRolePaymentsRoute,
    AccountRolePropertiesRoute: AccountRolePropertiesRoute,
    AccountRoleRepairsRoute: AccountRoleRepairsRoute,
    AccountRoleTenantsRoute: AccountRoleTenantsRoute,
    AccountRoleUtilitiesRoute: AccountRoleUtilitiesRoute,
    AccountRolePropertyIdRoute: AccountRolePropertyIdRoute,
};
const AccountRoleRouteWithChildren = AccountRoleRoute._addFileChildren(AccountRoleRouteChildren);
const AccountRouteChildren = {
    AccountRoleRoute: AccountRoleRouteWithChildren,
};
const AccountRouteWithChildren = AccountRoute._addFileChildren(AccountRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AccountRoute: AccountRouteWithChildren,
    LoginRoute: LoginRoute,
    RegisterRoute: RegisterRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
