/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRoleRouteImport } from './routes/account/$role'
import { Route as AccountRoleUtilitiesRouteImport } from './routes/account/$role/utilities'
import { Route as AccountRoleTenantsRouteImport } from './routes/account/$role/tenants'
import { Route as AccountRoleRepairsRouteImport } from './routes/account/$role/repairs'
import { Route as AccountRolePropertiesRouteImport } from './routes/account/$role/properties'
import { Route as AccountRolePaymentsRouteImport } from './routes/account/$role/payments'
import { Route as AccountRoleLandlordsRouteImport } from './routes/account/$role/landlords'
import { Route as AccountRoleHomeRouteImport } from './routes/account/$role/home'
import { Route as AccountRoleAdd_propertyRouteImport } from './routes/account/$role/add_property'
import { Route as AccountRoleAddRepairsRouteImport } from './routes/account/$role/add-repairs'
import { Route as AccountRoleAddPaymentRouteImport } from './routes/account/$role/add-payment'
import { Route as AccountRolePropertyIdRouteImport } from './routes/account/$role/property/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoleRoute = AccountRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRoleUtilitiesRoute = AccountRoleUtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRoleTenantsRoute = AccountRoleTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRoleRepairsRoute = AccountRoleRepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRolePropertiesRoute = AccountRolePropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRolePaymentsRoute = AccountRolePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRoleLandlordsRoute = AccountRoleLandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRoleHomeRoute = AccountRoleHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRoleAdd_propertyRoute = AccountRoleAdd_propertyRouteImport.update({
  id: '/add_property',
  path: '/add_property',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRoleAddRepairsRoute = AccountRoleAddRepairsRouteImport.update({
  id: '/add-repairs',
  path: '/add-repairs',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRoleAddPaymentRoute = AccountRoleAddPaymentRouteImport.update({
  id: '/add-payment',
  path: '/add-payment',
  getParentRoute: () => AccountRoleRoute,
} as any)
const AccountRolePropertyIdRoute = AccountRolePropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => AccountRoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/account/$role': typeof AccountRoleRouteWithChildren
  '/account/$role/add-payment': typeof AccountRoleAddPaymentRoute
  '/account/$role/add-repairs': typeof AccountRoleAddRepairsRoute
  '/account/$role/add_property': typeof AccountRoleAdd_propertyRoute
  '/account/$role/home': typeof AccountRoleHomeRoute
  '/account/$role/landlords': typeof AccountRoleLandlordsRoute
  '/account/$role/payments': typeof AccountRolePaymentsRoute
  '/account/$role/properties': typeof AccountRolePropertiesRoute
  '/account/$role/repairs': typeof AccountRoleRepairsRoute
  '/account/$role/tenants': typeof AccountRoleTenantsRoute
  '/account/$role/utilities': typeof AccountRoleUtilitiesRoute
  '/account/$role/property/$id': typeof AccountRolePropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/account/$role': typeof AccountRoleRouteWithChildren
  '/account/$role/add-payment': typeof AccountRoleAddPaymentRoute
  '/account/$role/add-repairs': typeof AccountRoleAddRepairsRoute
  '/account/$role/add_property': typeof AccountRoleAdd_propertyRoute
  '/account/$role/home': typeof AccountRoleHomeRoute
  '/account/$role/landlords': typeof AccountRoleLandlordsRoute
  '/account/$role/payments': typeof AccountRolePaymentsRoute
  '/account/$role/properties': typeof AccountRolePropertiesRoute
  '/account/$role/repairs': typeof AccountRoleRepairsRoute
  '/account/$role/tenants': typeof AccountRoleTenantsRoute
  '/account/$role/utilities': typeof AccountRoleUtilitiesRoute
  '/account/$role/property/$id': typeof AccountRolePropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/account/$role': typeof AccountRoleRouteWithChildren
  '/account/$role/add-payment': typeof AccountRoleAddPaymentRoute
  '/account/$role/add-repairs': typeof AccountRoleAddRepairsRoute
  '/account/$role/add_property': typeof AccountRoleAdd_propertyRoute
  '/account/$role/home': typeof AccountRoleHomeRoute
  '/account/$role/landlords': typeof AccountRoleLandlordsRoute
  '/account/$role/payments': typeof AccountRolePaymentsRoute
  '/account/$role/properties': typeof AccountRolePropertiesRoute
  '/account/$role/repairs': typeof AccountRoleRepairsRoute
  '/account/$role/tenants': typeof AccountRoleTenantsRoute
  '/account/$role/utilities': typeof AccountRoleUtilitiesRoute
  '/account/$role/property/$id': typeof AccountRolePropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/account/$role'
    | '/account/$role/add-payment'
    | '/account/$role/add-repairs'
    | '/account/$role/add_property'
    | '/account/$role/home'
    | '/account/$role/landlords'
    | '/account/$role/payments'
    | '/account/$role/properties'
    | '/account/$role/repairs'
    | '/account/$role/tenants'
    | '/account/$role/utilities'
    | '/account/$role/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/account/$role'
    | '/account/$role/add-payment'
    | '/account/$role/add-repairs'
    | '/account/$role/add_property'
    | '/account/$role/home'
    | '/account/$role/landlords'
    | '/account/$role/payments'
    | '/account/$role/properties'
    | '/account/$role/repairs'
    | '/account/$role/tenants'
    | '/account/$role/utilities'
    | '/account/$role/property/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/account/$role'
    | '/account/$role/add-payment'
    | '/account/$role/add-repairs'
    | '/account/$role/add_property'
    | '/account/$role/home'
    | '/account/$role/landlords'
    | '/account/$role/payments'
    | '/account/$role/properties'
    | '/account/$role/repairs'
    | '/account/$role/tenants'
    | '/account/$role/utilities'
    | '/account/$role/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$role': {
      id: '/account/$role'
      path: '/$role'
      fullPath: '/account/$role'
      preLoaderRoute: typeof AccountRoleRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/$role/utilities': {
      id: '/account/$role/utilities'
      path: '/utilities'
      fullPath: '/account/$role/utilities'
      preLoaderRoute: typeof AccountRoleUtilitiesRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/tenants': {
      id: '/account/$role/tenants'
      path: '/tenants'
      fullPath: '/account/$role/tenants'
      preLoaderRoute: typeof AccountRoleTenantsRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/repairs': {
      id: '/account/$role/repairs'
      path: '/repairs'
      fullPath: '/account/$role/repairs'
      preLoaderRoute: typeof AccountRoleRepairsRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/properties': {
      id: '/account/$role/properties'
      path: '/properties'
      fullPath: '/account/$role/properties'
      preLoaderRoute: typeof AccountRolePropertiesRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/payments': {
      id: '/account/$role/payments'
      path: '/payments'
      fullPath: '/account/$role/payments'
      preLoaderRoute: typeof AccountRolePaymentsRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/landlords': {
      id: '/account/$role/landlords'
      path: '/landlords'
      fullPath: '/account/$role/landlords'
      preLoaderRoute: typeof AccountRoleLandlordsRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/home': {
      id: '/account/$role/home'
      path: '/home'
      fullPath: '/account/$role/home'
      preLoaderRoute: typeof AccountRoleHomeRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/add_property': {
      id: '/account/$role/add_property'
      path: '/add_property'
      fullPath: '/account/$role/add_property'
      preLoaderRoute: typeof AccountRoleAdd_propertyRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/add-repairs': {
      id: '/account/$role/add-repairs'
      path: '/add-repairs'
      fullPath: '/account/$role/add-repairs'
      preLoaderRoute: typeof AccountRoleAddRepairsRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/add-payment': {
      id: '/account/$role/add-payment'
      path: '/add-payment'
      fullPath: '/account/$role/add-payment'
      preLoaderRoute: typeof AccountRoleAddPaymentRouteImport
      parentRoute: typeof AccountRoleRoute
    }
    '/account/$role/property/$id': {
      id: '/account/$role/property/$id'
      path: '/property/$id'
      fullPath: '/account/$role/property/$id'
      preLoaderRoute: typeof AccountRolePropertyIdRouteImport
      parentRoute: typeof AccountRoleRoute
    }
  }
}

interface AccountRoleRouteChildren {
  AccountRoleAddPaymentRoute: typeof AccountRoleAddPaymentRoute
  AccountRoleAddRepairsRoute: typeof AccountRoleAddRepairsRoute
  AccountRoleAdd_propertyRoute: typeof AccountRoleAdd_propertyRoute
  AccountRoleHomeRoute: typeof AccountRoleHomeRoute
  AccountRoleLandlordsRoute: typeof AccountRoleLandlordsRoute
  AccountRolePaymentsRoute: typeof AccountRolePaymentsRoute
  AccountRolePropertiesRoute: typeof AccountRolePropertiesRoute
  AccountRoleRepairsRoute: typeof AccountRoleRepairsRoute
  AccountRoleTenantsRoute: typeof AccountRoleTenantsRoute
  AccountRoleUtilitiesRoute: typeof AccountRoleUtilitiesRoute
  AccountRolePropertyIdRoute: typeof AccountRolePropertyIdRoute
}

const AccountRoleRouteChildren: AccountRoleRouteChildren = {
  AccountRoleAddPaymentRoute: AccountRoleAddPaymentRoute,
  AccountRoleAddRepairsRoute: AccountRoleAddRepairsRoute,
  AccountRoleAdd_propertyRoute: AccountRoleAdd_propertyRoute,
  AccountRoleHomeRoute: AccountRoleHomeRoute,
  AccountRoleLandlordsRoute: AccountRoleLandlordsRoute,
  AccountRolePaymentsRoute: AccountRolePaymentsRoute,
  AccountRolePropertiesRoute: AccountRolePropertiesRoute,
  AccountRoleRepairsRoute: AccountRoleRepairsRoute,
  AccountRoleTenantsRoute: AccountRoleTenantsRoute,
  AccountRoleUtilitiesRoute: AccountRoleUtilitiesRoute,
  AccountRolePropertyIdRoute: AccountRolePropertyIdRoute,
}

const AccountRoleRouteWithChildren = AccountRoleRoute._addFileChildren(
  AccountRoleRouteChildren,
)

interface AccountRouteChildren {
  AccountRoleRoute: typeof AccountRoleRouteWithChildren
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountRoleRoute: AccountRoleRouteWithChildren,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
